//Data

const products = [
  {
    productName: "Mini dinosaur",
    productImg: "img/p1 mini dinosaur.webp",
    productThum: {
      thum1: "img/p1.1.jpeg",
      thum2: "img/p1.2.jpeg",
      thum3: "img/p1.3.jpeg",
      thum4: "img/p1.4.jpeg",
      thum5: "img/p1.5.jpeg",
    },
    originalPrice: 133.99,
    salePercentage: 20, //20%
    gender: "girl",
    age: "0-2 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p2",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/p2.1.webp",
      thum2: "img/p2.1.webp",
      thum3: "img/p2.1.webp",
      thum4: "img/p2.1.webp",
      thum5: "img/p2.1.webp",
    },
    originalPrice: 33.99,
    salePercentage: 10,
    gender: "boy",
    age: "2-4 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p3",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 23.99,
    salePercentage: 10,
    gender: "unisex",
    age: "4-8 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p4",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 53.99,
    salePercentage: 30,
    gender: "boy",
    age: "8-12 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p5",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 83.99,
    salePercentage: 10,
    gender: "girl",
    age: "12+ years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p6",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 103.99,
    salePercentage: 20,
    gender: "boy",
    age: "8-12 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p7",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 63.99,
    salePercentage: 10,
    gender: "girl",
    age: "4-8 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p8",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 93.99,
    salePercentage: 20,
    gender: "boy",
    age: "2-4 years",
    brand: "nerf",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p9",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 136.99,
    salePercentage: 20,
    gender: "boy",
    age: "0-2 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p10",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 43.99,
    salePercentage: 30,
    gender: "unisex",
    age: "2-4 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p11",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 63.99,
    salePercentage: 20,
    gender: "boy",
    age: "4-8 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p12",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 83.99,
    salePercentage: 20,
    gender: "boy",
    age: "8-12 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p13",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 43.99,
    salePercentage: 10,
    gender: "unisex",
    age: "12+ years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p14",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 133.99,
    salePercentage: 20,
    gender: "boy",
    age: "0-2 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p15",
    productImg: "img/p1 mini dinosaur.webp",
    productThum: {
      thum1: "img/p1.1.jpeg",
      thum2: "img/p1.2.jpeg",
      thum3: "img/p1.3.jpeg",
      thum4: "img/p1.4.jpeg",
      thum5: "img/p1.5.jpeg",
    },
    originalPrice: 133.99,
    salePercentage: 30,
    gender: "boy",
    age: "2-4 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p16",
    productImg: "img/p2 laugh & learn 3in1.webp",
    productThum: {
      thum1: "img/p2.1.webp",
      thum2: "img/p2.1.webp",
      thum3: "img/p2.1.webp",
      thum4: "img/p2.1.webp",
      thum5: "img/p2.1.webp",
    },
    originalPrice: 13.99,
    salePercentage: 10,
    gender: "boy",
    age: "4-8 years",
    brand: "Hot wheels",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p17",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 93.99,
    salePercentage: 20,
    gender: "girl",
    age: "8-12 years",
    brand: "L.O.L Surprise",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p18",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 56.99,
    salePercentage: 30,
    gender: "boy",
    age: "12+ years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p19",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 100.99,
    salePercentage: 10,
    gender: "unisex",
    age: "0-2 years",
    brand: "L.O.L Surprise",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p20",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 123.99,
    salePercentage: 20,
    gender: "boy",
    age: "2-4 years",
    brand: "L.O.L Surprise",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p21",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 139.99,
    salePercentage: 30,
    gender: "boy",
    age: "0-2 years",
    brand: "fisher-price",
    category: "outdoor & sport toys",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p22",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 153.99,
    salePercentage: 20,
    gender: "girl",
    age: "0-2 years",
    brand: "barbie",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p23",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 203.99,
    salePercentage: 20,
    gender: "boy",
    age: "0-2 years",
    brand: "hot wheels",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p24",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 72.99,
    salePercentage: 10,
    gender: "unisex",
    age: "0-2 years",
    brand: "fisher-price",
    category: "building set toys",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p25",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 43.99,
    salePercentage: 20,
    gender: "boy",
    age: "0-2 years",
    brand: "nerf",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p26",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 67.99,
    salePercentage: 10,
    gender: "unisex",
    age: "0-2 years",
    brand: "fisher-price",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p27",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 93.99,
    salePercentage: 30,
    gender: "girl",
    age: "0-2 years",
    brand: "lego",
    category: "dolls & dollhouses",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
  {
    productName: "p28",
    productImg: "img/optimus.png",
    productThum: {
      thum1: "img/",
      thum2: "img/",
      thum3: "img/",
      thum4: "img/",
      thum5: "img/",
    },
    originalPrice: 63.99,
    salePercentage: 20,
    gender: "girl",
    age: "0-2 years",
    brand: "nerf",
    category: "games & puzzles",
    productType: ["do choi ngoai troi", "do choi van dong"],
    quantity: 1,
  },
];

//Product Slider
$(document).ready(function () {
  $(".product-slider").slick({
    slidesToShow: 4,
    slidesToScroll: 1,
    infinite: true,
    arrows: true,
    draggable: false,
    prevArrow: `<button type='button' class='slick-prev slick-arrow'><i class="fa-solid fa-chevron-left slick-arrow-btn" style="color: #ADB5BD;"></i></button>`,
    nextArrow: `<button type='button' class='slick-next slick-arrow'><i class="fa-solid fa-chevron-right slick-arrow-btn" style="color: #ADB5BD;"></button>`,
    dots: true,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 2,
          arrows: false,
          infinite: false,
        },
      },
    ],
  });
});

$(function () {
  $("#tab2").hide();
});
$(function () {
  $("#tabs-title-2").click(function () {
    $("#tabs-title-1").css("background-color", "#ffffff");
    $("#tabs-title-2").css("background-color", "#E9ECEF");
    $("#tab1").hide();
    $("#tab2").show();
  });
});
$(function () {
  $("#tabs-title-1").click(function () {
    $("#tabs-title-2").css("background-color", "#ffffff");
    $("#tabs-title-1").css("background-color", "#E9ECEF");
    $("#tab2").hide();
    $("#tab1").show();
    
  });
});
